---
title: "rowsum on Rle DataFrames"
author: "Charles Plessy"
date: "2023-06-30"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

## Purpose

There is no native `rowsum` function for `DataFrame`s of `Rle`-encoded
numerical values.  What is the best strategy for an implementation ?

## Setup

```{r setup}
library("CAGEr")   |> suppressPackageStartupMessages()
library("ggplot2") |> suppressPackageStartupMessages()
```

The DataFrame encodes counts of CAGE tags mapped on the zebrafish genome.

```{r define_data}
(DF <- CTSStagCountDF(exampleCAGEexp))
DF[[1]]

(names <- CTSScoordinatesGR(exampleCAGEexp)$cluster)
```

The functions:

```{r define_functions}
.rowsumDelayedArrayAsMatrix <- function(x, group, reorder = TRUE)
  rowsum(
    as.matrix(DelayedArray::DelayedArray(x)),
    group,
    reorder = reorder)
.rowsumDelayedArrayAsMatrix(DF, decode(names), reorder = FALSE) |> head()

.rowsumDelayedArrayAsdataframe <- function(x, group, reorder = TRUE)
  rowsum(
    as.data.frame(DelayedArray::DelayedArray(x)),
    group,
    reorder = reorder)
.rowsumDelayedArrayAsdataframe(DF, decode(names), reorder = FALSE) |> head()

.rowsumDecodeAsDF <- function(x, group, reorder = TRUE)
  rowsum(
    as.data.frame(lapply(x, decode)),
    group,
    reorder = reorder)
.rowsumDecodeAsDF(DF, decode(names), reorder = FALSE) |> head()
```

## Benchmark

```{r benchmark, fig.height=3, fig.width=9}
(microbench_out <- microbenchmark::microbenchmark(
  times = 100,
  .rowsumDelayedArrayAsMatrix = .rowsumDelayedArrayAsMatrix(DF, as.factor(names), reorder = FALSE),
  .rowsumDelayedArrayAsdataframe = .rowsumDelayedArrayAsdataframe(DF, as.factor(names), reorder = FALSE),
  .rowsumDecodeAsDF = .rowsumDecodeAsDF(DF, as.factor(names), reorder = FALSE)
))
# https://statisticsglobe.com/microbenchmark-package-r
ggplot(microbench_out, aes(x = time / 1e9, y = expr, color = expr)) +  # Plot performance comparison
  geom_boxplot() + 
  scale_x_log10("time (seconds)")
```

## Result

The winner is:

```
f_decode_reduce <- function(DF) Rle(Reduce(`+`, lapply(DF, decode), 0L))
```

Explained with more verbose code:

```
f_decode_reduce <- function(DF) {
  list_of_numerical_vectors <- lapply(DF, decode)
  parallel_sum              <- Reduce(`+`, list_of_numerical_vectors, 0L)
  result                    <- Rle(parallel_sum)
  return(result)
}
```

## Session information

```{r sessionInfo}
sessionInfo()
```